FROM node:lts-alpine

WORKDIR /usr/src/nuxt-app/

#copy only package.json for installing dependencies
COPY ./my_app/package.json .

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

#it takes time, depends on internet connection speed and dependencies size
RUN npm install --force

#after that, copy the whole app
COPY ./my_app .

#setting permissions, it takes time too..
RUN chown -R node ./node_modules
RUN chown -R node ./.nuxt

USER node

EXPOSE 3000

CMD [ "npm", "run", "dev" ]