#NUXTJS PRODUCTION MODE

FROM mhart/alpine-node:16.4.2

WORKDIR /usr/src/nuxt-app/

COPY ./my_app .

RUN npm install

RUN npm run build

RUN chown -R node ./node_modules
RUN chown -R node ./.nuxt

USER node

EXPOSE 3000

CMD [ "npm", "start" ]