#NUXTJS PRODUCTION MODE

FROM mhart/alpine-node:16.4.2

RUN apk add python3 make g++

WORKDIR /usr/src/nuxt-app/

COPY ./my_app .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]